=== ChekanKate/Epam_Tasks/jeirizai-task7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Hospital">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="MedicalCard"
                             type="MedicalCard" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="MedicalCard">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string" />
            <xsd:sequence>
                <xsd:element name="Diagnosis" type="Diagnosis" maxOccurs="4"/>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Diagnosis" mixed="true">
        <xsd:attribute name="healed" type="xsd:boolean" default="false" />
    </xsd:complexType>
</xsd:schema>

=== ChekanKate/Epam_Tasks/jeirizai-task7/input.xml
<?xml version="1.0" encoding="UTF-8"?>

<Hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="input.xsd">

    <MedicalCard>
        <Name>Kateryna</Name>
        <Diagnosis>Sore throat</Diagnosis>
        <Diagnosis healed="true">Headache</Diagnosis>
        <Diagnosis>Stomach ache</Diagnosis>
        <Diagnosis>Tooth pain</Diagnosis>
    </MedicalCard>

    <MedicalCard>
        <Name>Julia</Name>
        <Diagnosis>Headache</Diagnosis>
        <Diagnosis healed="true">Tooth pain</Diagnosis>
        <Diagnosis healed="true">Stomach ache</Diagnosis>
    </MedicalCard>

    <MedicalCard>
        <Name>Tom</Name>
        <Diagnosis>Headache</Diagnosis>
        <Diagnosis healed="true">Sore throat</Diagnosis>
    </MedicalCard>
</Hospital>
